import type { ComparisonPage } from '@/lib/discoveryTypes'
import { CONTENT_REVIEWER, LAST_REVIEWED_DATE } from '@/lib/site'

const reviewer = CONTENT_REVIEWER
const lastReviewed = LAST_REVIEWED_DATE

export const comparisonPages: Record<string, ComparisonPage> = {
  'png-vs-jpg': {
    slug: 'png-vs-jpg',
    title: 'PNG vs JPG',
    searchTitle: 'PNG vs JPG: Which Image Format Should You Use?',
    metaDescription: 'Compare PNG vs JPG for websites, screenshots, product photos, transparency, and file size so you can choose the right format faster.',
    description: 'A practical format comparison for common website and design workflows.',
    primaryIntent: 'png vs jpg',
    language: 'en',
    summary: 'Choose JPG for many photo-like web images and smaller file sizes. Choose PNG when transparency or lossless editing matters more.',
    bestChoice: 'JPG wins for many web photos and lightweight uploads. PNG wins for transparency, screenshots, and lossless next-step editing.',
    comparisonRows: [
      { label: 'File size', left: 'PNG is usually larger', right: 'JPG is usually smaller' },
      { label: 'Transparency', left: 'PNG supports it', right: 'JPG does not' },
      { label: 'Editing workflow', left: 'Better for lossless reuse', right: 'Better for final lightweight delivery' },
      { label: 'Best asset type', left: 'Screenshots, UI, logos', right: 'Photos, general marketing images' },
    ],
    winnerScenarios: ['Choose PNG for logos, screenshots, and transparent graphics.', 'Choose JPG for product photos, email, and general web uploads.'],
    faq: [
      { q: 'Is PNG always higher quality than JPG?', a: 'PNG is lossless, but that does not make it automatically “better” for every use case. It is just better for certain workflows.' },
      { q: 'Why do websites still use JPG so much?', a: 'Because many photo-heavy workflows care about smaller files and faster delivery more than transparency.' },
    ],
    relatedLinks: [
      { href: '/tools/png-to-jpg/', label: 'PNG to JPG converter', description: 'Switch to JPG when smaller size matters.' },
      { href: '/tools/jpg-to-png/', label: 'JPG to PNG converter', description: 'Switch to PNG for editing-friendly output.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Use the wider format-selection guide too.' },
    ],
    lastReviewed,
    reviewer,
  },
  'webp-vs-png': {
    slug: 'webp-vs-png',
    title: 'WebP vs PNG',
    searchTitle: 'WebP vs PNG: Which Format Should You Use?',
    metaDescription: 'Compare WebP vs PNG for web delivery, transparency, design handoff, and compatibility to choose the better image format.',
    description: 'A practical comparison between a modern web format and a widely compatible design-friendly format.',
    primaryIntent: 'webp vs png',
    language: 'en',
    summary: 'WebP is often better for smaller web delivery. PNG is better for broad compatibility and transparency-first editing workflows.',
    bestChoice: 'Choose WebP for smaller modern web assets when your stack supports it. Choose PNG for compatibility, transparency-safe reuse, and editing-friendly handoff.',
    comparisonRows: [
      { label: 'Web performance', left: 'PNG is often heavier', right: 'WebP is often lighter' },
      { label: 'Compatibility', left: 'PNG is broadly universal', right: 'WebP is modern but not always ideal in older workflows' },
      { label: 'Transparency support', left: 'Strong and common', right: 'Supported, but less preferred in some design flows' },
      { label: 'Best use', left: 'Design handoff, editing', right: 'Modern web delivery' },
    ],
    winnerScenarios: ['Choose WebP for modern website delivery when size matters.', 'Choose PNG when the next workflow expects an easy-to-open, transparency-safe file.'],
    faq: [
      { q: 'Is WebP always the better web choice?', a: 'Not always. It is often smaller, but workflow compatibility and editing needs still matter.' },
      { q: 'Why convert WebP to PNG at all?', a: 'Because design, CMS, and legacy workflows still often prefer PNG for easier handling.' },
    ],
    relatedLinks: [
      { href: '/tools/webp-to-png/', label: 'WebP to PNG converter', description: 'Fix compatibility quickly.' },
      { href: '/guides/how-to-convert-webp-to-png/', label: 'WebP to PNG guide', description: 'Use the task-focused workflow.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Make the wider format decision with more context.' },
    ],
    lastReviewed,
    reviewer,
  },
  'webp-vs-jpg': {
    slug: 'webp-vs-jpg',
    title: 'WebP vs JPG',
    searchTitle: 'WebP vs JPG: Which Should You Use?',
    metaDescription: 'Compare WebP vs JPG for compatibility, web performance, compression, and image delivery so you can pick the right format faster.',
    description: 'A format comparison focused on lightweight delivery and compatibility tradeoffs.',
    primaryIntent: 'webp vs jpg',
    language: 'en',
    summary: 'WebP is often better for modern compression. JPG is often better for universal compatibility and simpler sharing workflows.',
    bestChoice: 'Choose WebP for modern web delivery and smaller files. Choose JPG for broad compatibility, email, and older app support.',
    comparisonRows: [
      { label: 'Compression efficiency', left: 'Good, but older standard', right: 'Often better modern compression' },
      { label: 'Compatibility', left: 'Very broad', right: 'Good on the web, but not always ideal everywhere else' },
      { label: 'Transparency', left: 'No', right: 'Possible in some cases' },
      { label: 'Best use', left: 'General sharing and legacy support', right: 'Modern web optimization' },
    ],
    winnerScenarios: ['Choose JPG when you just need something to open everywhere.', 'Choose WebP when your website stack supports it well and size matters.'],
    faq: [
      { q: 'Should I convert all JPGs to WebP?', a: 'Not blindly. Use WebP where it helps delivery, but keep JPG where compatibility and workflow simplicity are more important.' },
      { q: 'Is JPG outdated now?', a: 'No. It is still one of the most practical general-purpose formats for many everyday workflows.' },
    ],
    relatedLinks: [
      { href: '/tools/webp-to-jpg/', label: 'WebP to JPG converter', description: 'Move back to a broadly compatible format.' },
      { href: '/guides/how-to-convert-webp-to-jpg/', label: 'WebP to JPG guide', description: 'Follow the practical workflow.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'See the wider web-format context.' },
    ],
    lastReviewed,
    reviewer,
  },
  'avif-vs-png': {
    slug: 'avif-vs-png',
    title: 'AVIF vs PNG',
    searchTitle: 'AVIF vs PNG: Compression vs Compatibility',
    metaDescription: 'Compare AVIF vs PNG for compatibility, compression, transparency, and editing workflows before choosing an export format.',
    description: 'A practical AVIF vs PNG comparison for modern web and design handoff workflows.',
    primaryIntent: 'avif vs png',
    language: 'en',
    summary: 'AVIF is often better for strong compression in supported environments. PNG is safer for compatibility, transparency, and editing handoff.',
    bestChoice: 'Choose AVIF when your workflow fully supports it and size matters. Choose PNG when compatibility and easier editing are more important.',
    comparisonRows: [
      { label: 'Compression', left: 'PNG is larger', right: 'AVIF is often much smaller' },
      { label: 'Compatibility', left: 'PNG is safer', right: 'AVIF support still varies more' },
      { label: 'Editing handoff', left: 'Better for design workflows', right: 'Less ideal in some legacy tools' },
      { label: 'Best use', left: 'Transparent and reusable assets', right: 'Efficient modern delivery' },
    ],
    winnerScenarios: ['Choose AVIF for supported modern web delivery.', 'Choose PNG when the next tool or teammate needs a more dependable format.'],
    faq: [
      { q: 'Why not always use AVIF if it is smaller?', a: 'Because workflow support and team comfort still matter. Smaller is not helpful if the next step breaks.' },
      { q: 'Why convert AVIF to PNG?', a: 'To regain compatibility and make editing or publishing handoff easier.' },
    ],
    relatedLinks: [
      { href: '/tools/avif-to-png/', label: 'AVIF to PNG converter', description: 'Fix the compatibility issue quickly.' },
      { href: '/guides/how-to-convert-avif-to-png/', label: 'AVIF to PNG guide', description: 'See the practical workflow.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Use the broader decision guide too.' },
    ],
    lastReviewed,
    reviewer,
  },
  'bijoy-vs-unicode': {
    slug: 'bijoy-vs-unicode',
    title: 'Bijoy vs Unicode',
    searchTitle: 'Bijoy vs Unicode: Which Bangla Workflow Should You Use?',
    metaDescription: 'Compare Bijoy vs Unicode for Bangla publishing, web use, legacy apps, and modern device compatibility.',
    description: 'A clear comparison page for choosing between legacy Bangla workflows and modern Unicode output.',
    primaryIntent: 'bijoy vs unicode',
    language: 'bn',
    summary: 'Unicode is the better default for modern web and app workflows. Bijoy still matters only when older publishing systems require it.',
    bestChoice: 'Choose Unicode for modern websites, docs, apps, and sharing. Choose Bijoy only when a legacy destination forces the requirement.',
    comparisonRows: [
      { label: 'Modern web compatibility', left: 'Weak', right: 'Strong' },
      { label: 'Legacy publishing support', left: 'Strong', right: 'Sometimes limited in older stacks' },
      { label: 'Mobile and cross-device readability', left: 'Weaker', right: 'Better' },
      { label: 'Best use', left: 'Older DTP environments', right: 'Modern publishing and communication' },
    ],
    winnerScenarios: ['Choose Unicode for almost every modern workflow.', 'Choose Bijoy only when an older publishing tool or client workflow still insists on it.'],
    faq: [
      { q: 'Should I migrate old Bangla text to Unicode?', a: 'Yes, when the goal is web publishing, modern documents, or better cross-device support.' },
      { q: 'Why does Bijoy still exist in workflows today?', a: 'Because some legacy publishing environments still depend on older fonts and conventions.' },
    ],
    relatedLinks: [
      { href: '/tools/bijoy-to-unicode/', label: 'Bijoy to Unicode', description: 'Move legacy text toward modern compatibility.' },
      { href: '/tools/unicode-to-bijoy/', label: 'Unicode to Bijoy', description: 'Bridge modern text back into a legacy environment when needed.' },
      { href: '/guides/fix-broken-bangla-font-conversion/', label: 'Fix broken Bangla conversion', description: 'Troubleshoot messy cross-standard results.' },
    ],
    lastReviewed,
    reviewer,
  },
  'json-formatter-vs-json-validator': {
    slug: 'json-formatter-vs-json-validator',
    title: 'JSON Formatter vs JSON Validator',
    searchTitle: 'JSON Formatter vs JSON Validator',
    metaDescription: 'Understand the difference between JSON formatting and JSON validation so you can choose the right developer workflow faster.',
    description: 'A developer-focused comparison page explaining what each JSON workflow actually does.',
    primaryIntent: 'json formatter vs json validator',
    language: 'en',
    summary: 'Formatting makes JSON readable. Validation tells you whether the JSON is structurally valid. Many practical tools do both, but they solve different moments in the workflow.',
    bestChoice: 'Use formatting when you need readability. Use validation when you need correctness. The best quick workflow is usually a tool that does both in one pass.',
    comparisonRows: [
      { label: 'Main job', left: 'Improves readability', right: 'Checks structural correctness' },
      { label: 'Best moment', left: 'After receiving messy JSON', right: 'Before shipping or reusing the data' },
      { label: 'Output', left: 'Indented or minified JSON', right: 'A pass/fail or error signal' },
      { label: 'Best use', left: 'Debugging and review', right: 'Verification and troubleshooting' },
    ],
    winnerScenarios: ['Format first when the payload is unreadable.', 'Validate when you need to confirm the JSON is safe to use.'],
    faq: [
      { q: 'Can a formatter also validate JSON?', a: 'Yes. Many practical tools do both because the workflows naturally overlap.' },
      { q: 'Do I still need validation if the JSON looks readable?', a: 'Yes. Good formatting does not guarantee the structure is valid.' },
    ],
    relatedLinks: [
      { href: '/tools/json-formatter/', label: 'Open JSON formatter', description: 'Format and validate JSON in one place.' },
      { href: '/all-tools/', label: 'Browse all tools', description: 'Move into other developer and utility workflows.' },
      { href: '/categories/developer-tools/', label: 'Developer tools hub', description: 'See the broader technical tool cluster.' },
    ],
    lastReviewed,
    reviewer,
  },
}
