import type { GuidePage } from '@/lib/discoveryTypes'
import { CONTENT_REVIEWER } from '@/lib/site'

const reviewer = CONTENT_REVIEWER
const lastReviewed = '2026-04-04'

export const englishWorkflowGuides: Record<string, GuidePage> = {
  'reduce-image-size-for-website': {
    slug: 'reduce-image-size-for-website',
    title: 'How to Reduce Image Size for a Website',
    searchTitle: 'Reduce Image Size for Website Uploads',
    metaDescription: 'Reduce image size for website uploads with the right compression, format, and dimension choices using a browser-based workflow.',
    description: 'A practical guide to reducing image weight before publishing to the web.',
    primaryIntent: 'reduce image size for website',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'Large images slow down pages, make CMS uploads harder, and hurt user experience. This page is built around the fastest way to shrink image files before they go live.',
    heroExample: {
      input: 'A heavy hero image or product photo heading to a website.',
      output: 'A smaller, faster-loading image with quality still acceptable for the page.',
      note: 'The goal is not "smallest possible," but "small enough without looking bad."',
    },
    steps: [
      'Upload the image to Image Compressor and start with moderate compression, not the strongest setting.',
      'Resize dimensions if the image is much larger than the display area on the site.',
      'Compare visual quality before downloading the optimized file.',
      'For photos, consider JPG or WebP workflows; for transparency, keep PNG where needed.',
    ],
    useCases: ['Page speed work', 'CMS uploads', 'Landing page optimization'],
    whenToUse: ['Before publishing website images', 'When file size is blocking uploads', 'When image-heavy pages feel slow'],
    avoidWhen: ['When the image is meant for print', 'When you need untouched archival quality'],
    faq: [
      { q: 'Should I resize dimensions or compress quality first?', a: 'Usually both. Start by checking if the image dimensions are far larger than the website actually displays.' },
      { q: 'What is a good website image workflow?', a: 'Choose the right format first, then compress moderately, then verify the image still looks acceptable on mobile and desktop.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Open image compressor', description: 'Reduce file size now.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Choose the right file type before exporting.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Match the format to the job.' },
    ],
    lastReviewed,
    reviewer,
  },
  'reduce-image-size-for-email': {
    slug: 'reduce-image-size-for-email',
    title: 'How to Reduce Image Size for Email',
    searchTitle: 'Reduce Image Size for Email Attachments',
    metaDescription: 'Reduce image size for email attachments and avoid oversized files with compression, resizing, and the right image format choices.',
    description: 'A quick email-focused compression workflow for oversized images.',
    primaryIntent: 'reduce image size for email',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'Email is one of the fastest places to hit file-size limits. This guide helps you shrink images for attachments without turning them into unreadable thumbnails.',
    heroExample: {
      input: 'A phone photo or screenshot that is too large to send comfortably.',
      output: 'A smaller image that still looks clear enough for inbox viewing.',
      note: 'This workflow is useful for teams, clients, and support messages that rely on screenshots or reference images.',
    },
    steps: [
      'Upload the image and start with moderate compression settings.',
      'Reduce dimensions if the image is much wider or taller than it needs to be for inbox reading.',
      'Download the optimized file and confirm it still looks clear at normal email viewing size.',
      'If you still need more savings, export a JPG from PNG where transparency is not required.',
    ],
    useCases: ['Support screenshots', 'Client attachments', 'Reference photos in inbox workflows'],
    whenToUse: ['When email rejects the file or sends slowly', 'When screenshots are larger than needed', 'When you want smaller attachments without heavy software'],
    avoidWhen: ['When the original file must remain untouched', 'When transparency is essential and email size is not a problem'],
    faq: [
      { q: 'Why are screenshots so large in email?', a: 'Screenshots can stay in PNG form with large dimensions, which makes them heavier than many email workflows need.' },
      { q: 'Should I use JPG for email?', a: 'Often yes for photos and general visuals, but keep PNG for interface shots or transparent assets when quality matters more.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Compress the image', description: 'Shrink the attachment before sending.' },
      { href: '/guides/how-to-convert-png-to-jpg/', label: 'PNG to JPG guide', description: 'Use JPG when file size matters more than transparency.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Pick the better email-friendly format.' },
    ],
    lastReviewed,
    reviewer,
  },
  'how-to-open-webp-files': {
    slug: 'how-to-open-webp-files',
    title: 'How to Open WebP Files',
    searchTitle: 'How to Open WebP Files on Any Device',
    metaDescription:
      'Learn how to open WebP files on Windows, Mac, mobile, and older apps, plus when to convert WebP to PNG or JPG for easier compatibility.',
    description: 'A practical troubleshooting guide for opening WebP images and converting them when the file format gets in the way.',
    primaryIntent: 'how to open webp files',
    language: 'en',
    toolSlug: 'webp-to-png',
    intro:
      'If a WebP file will not open, the problem is usually app support rather than the image itself. Some browsers and modern editors handle WebP easily, while older software, office apps, and certain upload workflows still do not. This guide helps you decide whether to open the file as-is or convert it into a more dependable format.',
    heroExample: {
      input: 'A .webp image downloaded from a website that opens in the browser but not in your editor, document workflow, or older app.',
      output: 'A practical next step: either open the file in a supported app or convert it into PNG or JPG for broader compatibility.',
      note: 'This page is designed to solve the real problem quickly instead of forcing users into random software installs or extension hacks.',
    },
    sections: [
      {
        heading: 'Why WebP files sometimes will not open',
        paragraphs: [
          'WebP is a modern web format, so it works best in browsers and current software stacks. Problems usually appear when the file moves into older desktop apps, office workflows, legacy CMS setups, or tools that were built around JPG and PNG.',
          'In other words, a WebP file is not usually broken. The destination app is often the weak point. That is why the best fix can be either opening it differently or converting it into a safer format for the next workflow.',
        ],
      },
      {
        heading: 'Open first, convert second',
        paragraphs: [
          'If your goal is only to view the image, try opening the WebP file in a modern browser first. Dragging the file into Chrome, Edge, or another current browser is often enough.',
          'If your goal is to edit, upload, insert into a document, or share with someone using older tools, conversion is usually faster than troubleshooting app support.',
        ],
        bullets: [
          'Open in a modern browser when you only need to view the image.',
          'Convert to PNG when you need transparency or better editing compatibility.',
          'Convert to JPG when you need a smaller file that opens almost everywhere.',
        ],
      },
      {
        heading: 'When to convert WebP to PNG or JPG',
        paragraphs: [
          'Choose PNG when the next workflow involves design, transparency, screenshots, or a tool that behaves better with lossless image formats.',
          'Choose JPG when the real goal is simple compatibility, email sharing, or a lighter file for everyday delivery. The format choice should follow the next job, not just the current error message.',
        ],
      },
    ],
    steps: [
      'Try opening the WebP file in a current browser first if you only need to view it.',
      'If the destination app still refuses the file, decide whether you need PNG compatibility or a lighter JPG output.',
      'Use WebP to PNG when transparency, editing flexibility, or design-tool support matters.',
      'Use WebP to JPG when the goal is broad compatibility and a smaller final file.',
    ],
    useCases: ['Opening downloads from websites', 'Fixing unsupported file types in older apps', 'Converting WebP for office, CMS, and design workflows'],
    whenToUse: [
      'When a downloaded WebP image will not open in the next app',
      'When you need a practical compatibility fix instead of troubleshooting software support',
      'When you are not sure whether to keep the file as WebP or convert it',
    ],
    avoidWhen: [
      'When your current browser or app already handles WebP correctly and no conversion is needed',
      'When you are dealing with a damaged file rather than a format-support issue',
    ],
    faq: [
      {
        q: 'Can I open WebP files without converting them?',
        a: 'Yes. Modern browsers and many newer apps open WebP files directly. Conversion is only necessary when the next workflow does not support the format well.',
      },
      {
        q: 'Should I convert WebP to PNG or JPG?',
        a: 'Use PNG when transparency, editing, or design handoff matters. Use JPG when you mainly need a smaller, broadly compatible file for sharing or upload.',
      },
      {
        q: 'Why do WebP files open in the browser but not in some apps?',
        a: 'Because browser support is generally strong, while some older desktop applications and office workflows still expect JPG or PNG.',
      },
    ],
    relatedLinks: [
      { href: '/tools/webp-to-png/', label: 'WebP to PNG converter', description: 'Use PNG when you need the safer compatibility path.' },
      { href: '/guides/how-to-convert-webp-to-png/', label: 'How to convert WebP to PNG', description: 'Follow the flagship WebP-to-PNG workflow guide.' },
      { href: '/tools/webp-to-jpg/', label: 'WebP to JPG converter', description: 'Use JPG when you want a lighter universal file.' },
      { href: '/compare/webp-vs-png/', label: 'WebP vs PNG', description: 'Compare the two formats before choosing a conversion target.' },
    ],
    lastReviewed,
    reviewer,
  },
  'compress-images-for-shopify': {
    slug: 'compress-images-for-shopify',
    title: 'How to Compress Images for Shopify',
    searchTitle: 'Compress Images for Shopify Product Pages',
    metaDescription: 'Compress Shopify product and collection images for faster loads without wrecking visual quality using browser-based tools.',
    description: 'A Shopify-friendly image optimization workflow for product and collection pages.',
    primaryIntent: 'compress images for shopify',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'Shopify stores depend on clean product images, but large files can slow pages down and make theme sections feel heavy. This guide focuses on getting images smaller before upload.',
    heroExample: {
      input: 'A batch of product photos exported too large from a camera or design tool.',
      output: 'Smaller, store-ready images that preserve enough quality for ecommerce display.',
      note: 'The priority is a balance between trust-building visuals and faster product pages.',
    },
    steps: [
      'Compress each product image before upload, starting with moderate settings instead of maximum compression.',
      'Resize oversized images so the final dimensions match real storefront usage more closely.',
      'Keep transparency only where the product design actually needs it.',
      'Review the optimized files on a mobile-width preview before final upload.',
    ],
    useCases: ['Product pages', 'Collection pages', 'Homepage merchandising assets'],
    whenToUse: ['Before uploading product batches', 'When pages feel image-heavy', 'When you want cleaner ecommerce performance'],
    avoidWhen: ['When a print or zoom workflow needs the original large file', 'When assets will still go through major editing later'],
    faq: [
      { q: 'Should all Shopify product photos be JPG?', a: 'Not always. JPG is often the better default for photos, but PNG still matters for transparency-heavy assets.' },
      { q: 'Is resizing just as important as compression?', a: 'Yes. Oversized dimensions are a common reason ecommerce images stay heavier than they need to be.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Compress images now', description: 'Optimize product photos before upload.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Choose formats more intentionally for ecommerce.' },
      { href: '/tools/background-remover/', label: 'Background remover', description: 'Prepare cleaner product shots before compression.' },
    ],
    lastReviewed,
    reviewer,
  },
  'compress-images-for-wordpress': {
    slug: 'compress-images-for-wordpress',
    title: 'How to Compress Images for WordPress',
    searchTitle: 'Compress Images for WordPress Uploads',
    metaDescription: 'Compress and resize WordPress images before upload to reduce page weight and make media workflows easier.',
    description: 'A pre-upload image optimization workflow for WordPress content teams.',
    primaryIntent: 'compress images for wordpress',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'WordPress content editors often upload images that are much larger than the page actually needs. This guide helps you reduce weight before the file ever touches the media library.',
    heroExample: {
      input: 'A large blog image prepared for a WordPress post.',
      output: 'A smaller, cleaner file that is easier to upload and faster on the front end.',
      note: 'This is a pre-upload optimization workflow, not a plugin replacement.',
    },
    steps: [
      'Open Image Compressor and upload the WordPress image asset before adding it to the media library.',
      'Reduce dimensions if the file is significantly larger than the article layout requires.',
      'Use moderate compression and compare clarity before download.',
      'Upload the optimized file into WordPress instead of the original large asset.',
    ],
    useCases: ['Blog cover images', 'Article screenshots', 'Feature images'],
    whenToUse: ['Before media library uploads', 'When WordPress pages feel slow', 'When editors want lighter image files without plugins'],
    avoidWhen: ['When a media automation plugin already handles the exact workflow well', 'When the file is still in an active design stage'],
    faq: [
      { q: 'Why optimize before upload instead of after?', a: 'Pre-upload optimization keeps the library cleaner and avoids publishing oversized files in the first place.' },
      { q: 'Should WordPress feature images be huge?', a: 'Not usually. Match the actual display size more closely instead of uploading unnecessarily large originals.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Open image compressor', description: 'Optimize the file before it hits WordPress.' },
      { href: '/guides/reduce-image-size-for-website/', label: 'Reduce image size for a website', description: 'Use the more general workflow too.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Choose a better default format for WordPress media.' },
    ],
    lastReviewed,
    reviewer,
  },
  'remove-background-from-product-photo': {
    slug: 'remove-background-from-product-photo',
    title: 'How to Remove Background from a Product Photo',
    searchTitle: 'Remove Background from Product Photo Online',
    metaDescription: 'Remove the background from product photos online and create transparent PNGs for catalogs, listings, and design comps.',
    description: 'A product-photo-specific cutout workflow built around transparent output.',
    primaryIntent: 'remove background from product photo',
    language: 'en',
    toolSlug: 'background-remover',
    intro: 'Product images are one of the clearest use cases for fast background removal. This guide keeps the workflow focused on ecommerce and catalog-style results.',
    heroExample: {
      input: 'A product shot taken on a desk or simple backdrop.',
      output: 'A transparent PNG that can sit cleanly on white, branded, or marketplace backgrounds.',
      note: 'The simpler the product edge and background contrast, the better the quick-cut result tends to be.',
    },
    steps: [
      'Upload the product photo into Background Remover.',
      'Generate the cutout and review the edges around the item.',
      'Download the transparent PNG.',
      'Use Image Compressor if the PNG needs to be lighter for a listing or page.',
    ],
    useCases: ['Marketplace listings', 'Catalog cards', 'Promo graphics'],
    whenToUse: ['When the product needs to sit on multiple backgrounds', 'When listings need a cleaner visual presentation', 'When manual masking would take too long'],
    avoidWhen: ['When the subject has extremely complex edges', 'When the final image still requires studio-grade retouching'],
    faq: [
      { q: 'Is PNG the best output for product cutouts?', a: 'Usually yes, because PNG handles transparency well and is easy to reuse across different backgrounds.' },
      { q: 'Can I use this for complex reflective products?', a: 'Yes, but reflective or low-contrast products may still need manual cleanup after the quick cutout.' },
    ],
    relatedLinks: [
      { href: '/tools/background-remover/', label: 'Open background remover', description: 'Create the cutout now.' },
      { href: '/guides/how-to-make-a-transparent-png/', label: 'Transparent PNG guide', description: 'See the broader transparent asset workflow.' },
      { href: '/tools/image-compress/', label: 'Compress the PNG', description: 'Make the final asset lighter for storefront use.' },
    ],
    lastReviewed,
    reviewer,
  },
  'how-to-make-a-transparent-png': {
    slug: 'how-to-make-a-transparent-png',
    title: 'How to Make a Transparent PNG',
    searchTitle: 'How to Make a Transparent PNG Online',
    metaDescription:
      'Make a transparent PNG online by removing the background from an image, keeping clean edges, and exporting a reusable transparent file.',
    description: 'A broader transparency workflow guide for removing backgrounds and creating transparent PNGs that are actually usable.',
    primaryIntent: 'how to make a transparent png',
    language: 'en',
    toolSlug: 'background-remover',
    intro:
      'Most people who want a transparent PNG are really trying to remove a background cleanly so the subject can be reused somewhere else. That might be a product photo, logo-style cutout, profile image, or design asset. The practical workflow is to remove the background first, then export a transparent PNG that will behave correctly on different backgrounds.',
    heroExample: {
      input: 'A photo or graphic with a background that needs to disappear.',
      output: 'A transparent PNG ready for ecommerce, presentations, social graphics, or design comps.',
      note: 'This page now covers the broader problem users actually have: creating transparency, not just naming the output format.',
    },
    sections: [
      {
        heading: 'What a transparent PNG solves',
        paragraphs: [
          'A transparent PNG lets the visible subject sit cleanly on white, dark, branded, or layered backgrounds without bringing the original backdrop along with it.',
          'That makes it useful for product cards, marketing graphics, profile cutouts, slides, and many quick design workflows where a plain rectangular photo feels awkward or limiting.',
        ],
      },
      {
        heading: 'The practical workflow: remove background, then export',
        paragraphs: [
          'The important point is that transparency usually comes from background removal, not from a simple file conversion. Converting JPG to PNG or WebP to PNG alone does not magically remove the background.',
          'That is why the best workflow is to start with a background-removal tool, review the edges, then export the result as PNG so the transparency survives in the final file.',
        ],
        bullets: [
          'Use PNG because it is broadly supported for transparent output.',
          'Check hair, shadows, and edge detail before downloading the final file.',
          'Compress the PNG afterward if the file becomes too heavy for web use.',
        ],
      },
    ],
    steps: [
      'Open Background Remover and upload the source image.',
      'Generate the cutout and review the edges around the subject carefully.',
      'Download the transparent PNG output.',
      'If the PNG is heavier than needed, compress it after export rather than flattening it back into a non-transparent format.',
    ],
    useCases: ['Product cards', 'Profile graphics', 'Presentation and ad design'],
    whenToUse: [
      'When the subject needs to sit on multiple backgrounds',
      'When a transparent file is required for design or ecommerce work',
      'When you want a reusable cutout instead of a standard rectangular image',
    ],
    avoidWhen: [
      'When the final output can keep a solid background',
      'When the image needs heavy manual retouching beyond quick background removal',
    ],
    faq: [
      {
        q: 'Why use PNG for transparency?',
        a: 'PNG is one of the most common broadly supported formats for transparent images in web, design, ecommerce, and document workflows.',
      },
      {
        q: 'Can I make a transparent PNG by converting JPG to PNG?',
        a: 'No. A format conversion alone does not remove the background. You need background removal first, then PNG export.',
      },
      {
        q: 'What if my transparent PNG file is too large?',
        a: 'That is common. PNG preserves transparency well, but the file can grow. Compress the PNG afterward if you need a lighter web or upload version.',
      },
    ],
    relatedLinks: [
      { href: '/tools/background-remover/', label: 'Open background remover', description: 'Create the transparent PNG now.' },
      { href: '/guides/remove-background-from-product-photo/', label: 'Remove background from a product photo', description: 'Use the more ecommerce-specific workflow when the image is a product shot.' },
      { href: '/tools/image-compress/', label: 'Compress transparent PNGs', description: 'Reduce file size after export.' },
      { href: '/guides/how-to-convert-jpg-to-png/', label: 'How to convert JPG to PNG', description: 'Use the adjacent guide when your real problem is format conversion before editing.' },
    ],
    lastReviewed,
    reviewer,
  },
  'best-format-for-website-images': {
    slug: 'best-format-for-website-images',
    title: 'Best Format for Website Images',
    searchTitle: 'Best Format for Website Images: PNG, JPG, WebP, or AVIF?',
    metaDescription: 'Choose the best website image format for speed, transparency, quality, and compatibility with this practical format-selection guide.',
    description: 'A format selection guide for website image workflows across PNG, JPG, WebP, and AVIF.',
    primaryIntent: 'best format for website images',
    language: 'en',
    toolSlug: 'image-converter',
    intro: 'There is no single "best" image format for every page. This guide helps you choose based on speed, compatibility, and whether transparency matters.',
    heroExample: {
      input: 'A mix of product photos, screenshots, and graphics heading to a website.',
      output: 'A clearer format choice for each asset type instead of using one format blindly.',
      note: 'The right format is usually "best for this use case," not "best forever."',
    },
    steps: [
      'Use JPG for many photos and general marketing images where smaller size matters.',
      'Use PNG for transparency-heavy graphics, screenshots, and design assets that need lossless output.',
      'Use WebP when you want smaller modern web assets and the stack supports it well.',
      'Use AVIF selectively when your workflow and audience support it and you want strong compression.',
    ],
    useCases: ['Website publishing', 'CMS uploads', 'Content-team workflows'],
    whenToUse: ['When building a repeatable image workflow', 'When deciding between speed and compatibility', 'When page speed and appearance both matter'],
    avoidWhen: ['When the task is just a one-off conversion and the format is already decided', 'When the real problem is image dimensions, not format choice'],
    faq: [
      { q: 'Is WebP always the best web format?', a: 'Not always. WebP is often a strong choice, but PNG and JPG still win in some transparency, editing, or compatibility cases.' },
      { q: 'Should I use AVIF everywhere?', a: 'No. AVIF can be excellent, but support and workflow comfort still vary across teams and tools.' },
    ],
    relatedLinks: [
      { href: '/tools/image-converter/', label: 'Open image converter', description: 'Switch formats once you know the right target.' },
      { href: '/guides/reduce-image-size-for-website/', label: 'Reduce image size for a website', description: 'Use the broader optimization workflow after choosing a format.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Compare the two most common defaults.' },
      { href: '/compare/webp-vs-png/', label: 'WebP vs PNG', description: 'Choose between smaller modern files and transparency-safe output.' },
    ],
    lastReviewed,
    reviewer,
  },
}
