import type { GuidePage } from '@/lib/discoveryTypes'
import { CONTENT_REVIEWER, LAST_REVIEWED_DATE } from '@/lib/site'

const reviewer = CONTENT_REVIEWER
const lastReviewed = LAST_REVIEWED_DATE

export const englishConversionGuides: Record<string, GuidePage> = {
  'how-to-convert-webp-to-png': {
    slug: 'how-to-convert-webp-to-png',
    title: 'How to Convert WebP to PNG',
    searchTitle: 'How to Convert WebP to PNG Online',
    metaDescription: 'Convert WebP to PNG in the browser with step-by-step guidance, example inputs, and the best times to use PNG output.',
    description: 'A practical walkthrough for converting WebP files into more widely compatible PNG images.',
    primaryIntent: 'how to convert webp to png',
    language: 'en',
    toolSlug: 'webp-to-png',
    intro: 'Use this guide when a WebP file is blocking your workflow because the next tool, app, or CMS expects PNG. The goal is simple: keep transparency when available, download a cleaner PNG, and move on quickly.',
    heroExample: {
      input: 'A WebP product image downloaded from a website.',
      output: 'A transparent PNG that opens cleanly in design or marketplace workflows.',
      note: 'This is one of the fastest compatibility fixes for ecommerce and design handoff.',
    },
    steps: [
      'Open the dedicated WebP to PNG converter and upload the source image.',
      'Wait for the browser-based conversion to complete on your device.',
      'Preview the PNG result and confirm that transparency or quality looks correct.',
      'Download the PNG and use Image Compressor next if the file is larger than expected.',
    ],
    useCases: ['Design handoff', 'Marketplace image cleanup', 'Transparent asset export'],
    whenToUse: ['When the next app does not handle WebP well', 'When you need transparency preserved', 'When you want an easier-to-edit export'],
    avoidWhen: ['When tiny file size matters more than compatibility', 'When WebP already works fine in the target workflow'],
    faq: [
      { q: 'Does converting WebP to PNG keep transparency?', a: 'Yes, when the original WebP contains transparency, PNG is the safer export format for preserving it.' },
      { q: 'Will the PNG be larger than the WebP?', a: 'Usually yes. PNG is lossless and often bigger, so the next step is often compression if weight matters.' },
    ],
    relatedLinks: [
      { href: '/tools/webp-to-png/', label: 'Open the converter', description: 'Run the actual WebP to PNG workflow.' },
      { href: '/compare/webp-vs-png/', label: 'WebP vs PNG', description: 'See when each format is the better choice.' },
      { href: '/guides/how-to-make-a-transparent-png/', label: 'Transparent PNG guide', description: 'Use PNG output well after conversion.' },
    ],
    lastReviewed,
    reviewer,
  },
  'how-to-convert-png-to-jpg': {
    slug: 'how-to-convert-png-to-jpg',
    title: 'How to Convert PNG to JPG',
    searchTitle: 'How to Convert PNG to JPG Online',
    metaDescription: 'Convert PNG to JPG with a simple browser workflow, learn when JPG is the right format, and avoid common transparency mistakes.',
    description: 'A practical PNG to JPG workflow for smaller file sizes and easier uploads.',
    primaryIntent: 'how to convert png to jpg',
    language: 'en',
    toolSlug: 'png-to-jpg',
    intro: 'Use PNG to JPG when you need a smaller file for the web, email, or marketplace uploads and you do not need transparency anymore.',
    heroExample: {
      input: 'A large PNG screenshot or product image.',
      output: 'A lighter JPG that is easier to upload and quicker to load.',
      note: 'Use this when file size matters more than transparency.',
    },
    steps: [
      'Open the PNG to JPG converter and upload the PNG image.',
      'Let the browser create the JPG version locally on your device.',
      'Preview the exported JPG and confirm the background flattening looks acceptable.',
      'Download the JPG and keep the original PNG if you still need an editable source.',
    ],
    useCases: ['Website uploads', 'Email attachments', 'Marketplace product listings'],
    whenToUse: ['When file size matters', 'When the image does not need transparency', 'When you want universal JPG support'],
    avoidWhen: ['When logos or UI elements need transparent backgrounds', 'When you are archiving assets for repeated editing'],
    faq: [
      { q: 'What happens to transparent PNG areas?', a: 'JPG does not support transparency, so transparent areas are flattened into a solid background.' },
      { q: 'Why use PNG to JPG instead of compression?', a: 'Sometimes the format switch alone gives a better size reduction, especially for photo-like images.' },
    ],
    relatedLinks: [
      { href: '/tools/png-to-jpg/', label: 'Open PNG to JPG', description: 'Convert the image now.' },
      { href: '/tools/image-compress/', label: 'Compress images', description: 'Reduce file size even more after export.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Choose the right format for the next upload.' },
    ],
    lastReviewed,
    reviewer,
  },
  'how-to-convert-jpg-to-png': {
    slug: 'how-to-convert-jpg-to-png',
    title: 'How to Convert JPG to PNG',
    searchTitle: 'How to Convert JPG to PNG Online',
    metaDescription: 'Convert JPG to PNG in the browser and learn when PNG is worth the larger file size for editing, screenshots, and design workflows.',
    description: 'A straightforward guide for moving JPG files into a lossless PNG workflow.',
    primaryIntent: 'how to convert jpg to png',
    language: 'en',
    toolSlug: 'jpg-to-png',
    intro: 'Use JPG to PNG when the next step is editing, annotation, or design handoff and you want a lossless file format for the next stage.',
    heroExample: {
      input: 'A JPG screen capture that will be annotated in a presentation.',
      output: 'A PNG version that fits better into a lossless editing workflow.',
      note: 'This helps the next edit stage, but it does not recover detail already lost in JPG compression.',
    },
    steps: [
      'Open the JPG to PNG converter and upload the JPG file.',
      'Run the local browser conversion and preview the PNG output.',
      'Download the PNG for the next editing or export step.',
      'If you need transparency later, pair the output with Background Remover instead of expecting the conversion alone to create it.',
    ],
    useCases: ['Presentation markup', 'Design handoff', 'Screenshot cleanup'],
    whenToUse: ['When the next step should be lossless', 'When you want consistency across PNG-based assets', 'When you need a safer format for repeated re-export'],
    avoidWhen: ['When small file size matters most', 'When the JPG is the final delivery format already'],
    faq: [
      { q: 'Does converting JPG to PNG improve image quality?', a: 'No. It preserves the current state in a lossless output, but it does not restore lost detail from earlier JPG compression.' },
      { q: 'Why use PNG after JPG?', a: 'PNG is better for the next editing stage when you want to avoid adding more lossy compression.' },
    ],
    relatedLinks: [
      { href: '/tools/jpg-to-png/', label: 'Open JPG to PNG', description: 'Convert the file now.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Understand the tradeoff before exporting.' },
      { href: '/tools/background-remover/', label: 'Background remover', description: 'Create transparent output if that is your real next step.' },
    ],
    lastReviewed,
    reviewer,
  },
  'how-to-convert-webp-to-jpg': {
    slug: 'how-to-convert-webp-to-jpg',
    title: 'How to Convert WebP to JPG',
    searchTitle: 'How to Convert WebP to JPG Online',
    metaDescription: 'Turn WebP files into JPG for broad compatibility with older apps, email, and listings with this simple browser guide.',
    description: 'A quick WebP to JPG workflow for broad compatibility and smaller upload-friendly files.',
    primaryIntent: 'how to convert webp to jpg',
    language: 'en',
    toolSlug: 'webp-to-jpg',
    intro: 'Use WebP to JPG when you want broad compatibility and a lighter export, and you do not need transparency in the output.',
    heroExample: {
      input: 'A WebP image downloaded from a website or CMS.',
      output: 'A universal JPG that works almost anywhere.',
      note: 'This is the safest “just make it open everywhere” path when transparency is not required.',
    },
    steps: [
      'Open the WebP to JPG converter and upload the source file.',
      'Run the in-browser conversion and preview the flattened result.',
      'Download the JPG for upload, sharing, or archiving.',
      'Use JPG to PNG later only if the next workflow needs a lossless output format.',
    ],
    useCases: ['Email attachments', 'CMS uploads', 'General compatibility fixes'],
    whenToUse: ['When the target app supports JPG more reliably', 'When you want a smaller file than PNG', 'When transparency is not important'],
    avoidWhen: ['When you must preserve transparent areas', 'When design editing is the next main workflow'],
    faq: [
      { q: 'Should I choose WebP to JPG or WebP to PNG?', a: 'Choose JPG for smaller universal files and PNG when you need transparency or a lossless next format.' },
      { q: 'Is JPG the best final delivery format?', a: 'For many web and sharing use cases, yes, but not for every design or transparent asset workflow.' },
    ],
    relatedLinks: [
      { href: '/tools/webp-to-jpg/', label: 'Open WebP to JPG', description: 'Run the actual conversion.' },
      { href: '/compare/webp-vs-jpg/', label: 'WebP vs JPG', description: 'Choose the better format for the next step.' },
      { href: '/tools/image-compress/', label: 'Compress images', description: 'Trim file size further if needed.' },
    ],
    lastReviewed,
    reviewer,
  },
  'how-to-convert-avif-to-png': {
    slug: 'how-to-convert-avif-to-png',
    title: 'How to Convert AVIF to PNG',
    searchTitle: 'How to Convert AVIF to PNG Online',
    metaDescription: 'Convert AVIF to PNG to fix compatibility issues with older apps and design workflows while keeping a lossless output format.',
    description: 'A simple AVIF to PNG path for compatibility and editing-friendly output.',
    primaryIntent: 'how to convert avif to png',
    language: 'en',
    toolSlug: 'avif-to-png',
    intro: 'AVIF is efficient, but support can still be inconsistent in older design, publishing, and enterprise workflows. This guide helps you convert it into a safer PNG export quickly.',
    heroExample: {
      input: 'An AVIF image that will not open in a target editor.',
      output: 'A PNG export that fits better into design and publishing workflows.',
      note: 'This page exists because AVIF support still varies across apps and teams.',
    },
    steps: [
      'Open the AVIF to PNG converter and upload the AVIF file.',
      'Run the browser conversion and preview the PNG output.',
      'Download the PNG and confirm the new file works in the target application.',
      'If the output is too large, use Image Compressor on the PNG or switch to JPG when transparency is not needed.',
    ],
    useCases: ['Older app compatibility', 'Design handoff', 'Editing-friendly exports'],
    whenToUse: ['When AVIF support is blocking delivery', 'When you need a lossless follow-up format', 'When transparency or editing matters more than the smallest size'],
    avoidWhen: ['When the target app already handles AVIF correctly', 'When smallest file size is the top priority'],
    faq: [
      { q: 'Why convert AVIF to PNG instead of AVIF to JPG?', a: 'PNG is the safer choice when you want a lossless output and editing-friendly format, especially for graphics or assets with transparency.' },
      { q: 'Will the PNG be much larger?', a: 'Often yes. AVIF is highly compressed, while PNG is typically larger but more compatible in older workflows.' },
    ],
    relatedLinks: [
      { href: '/tools/avif-to-png/', label: 'Open AVIF to PNG', description: 'Convert the file now.' },
      { href: '/compare/avif-vs-png/', label: 'AVIF vs PNG', description: 'Understand why the formats behave differently.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Pick the right format after the compatibility fix.' },
    ],
    lastReviewed,
    reviewer,
  },
  'how-to-make-a-transparent-png': {
    slug: 'how-to-make-a-transparent-png',
    title: 'How to Make a Transparent PNG',
    searchTitle: 'How to Make a Transparent PNG Online',
    metaDescription: 'Make a transparent PNG by removing the background in the browser, then export a clean result for products, logos, and graphics.',
    description: 'A step-by-step page for creating transparent PNG files from regular photos or assets.',
    primaryIntent: 'how to make a transparent png',
    language: 'en',
    toolSlug: 'background-remover',
    intro: 'Creating a transparent PNG usually means removing the background first, then exporting the subject in PNG format. This page is built for that exact workflow.',
    heroExample: {
      input: 'A photo of a product with a distracting backdrop.',
      output: 'A transparent PNG ready for ecommerce, ads, and design comps.',
      note: 'This is a high-intent page because the user already knows the output they want.',
    },
    steps: [
      'Open Background Remover and upload the source image.',
      'Generate the cutout and check the edges around the subject.',
      'Download the transparent PNG output.',
      'Use Image Compressor afterward if you need a lighter transparent asset.',
    ],
    useCases: ['Product cards', 'Profile graphics', 'Presentation and ad design'],
    whenToUse: ['When the subject needs to sit on multiple backgrounds', 'When a transparent file is required', 'When PNG is the expected design handoff format'],
    avoidWhen: ['When the final output can keep a solid background', 'When the image still needs heavy manual retouching'],
    faq: [
      { q: 'Why use PNG for transparency?', a: 'PNG is the most common broadly supported format for transparent backgrounds in design, web, and ecommerce workflows.' },
      { q: 'Can JPG be transparent?', a: 'No. JPG does not support transparency, so you need PNG or another transparency-capable format.' },
    ],
    relatedLinks: [
      { href: '/tools/background-remover/', label: 'Open background remover', description: 'Create the transparent PNG now.' },
      { href: '/guides/remove-background-from-product-photo/', label: 'Remove product photo backgrounds', description: 'Use the workflow for ecommerce images.' },
      { href: '/tools/image-compress/', label: 'Compress transparent PNGs', description: 'Reduce file size after export.' },
    ],
    lastReviewed,
    reviewer,
  },
}
