import type { GuidePage } from '@/lib/discoveryTypes'
import { CONTENT_REVIEWER, LAST_REVIEWED_DATE } from '@/lib/site'

const reviewer = CONTENT_REVIEWER
const lastReviewed = LAST_REVIEWED_DATE

export const englishWorkflowGuides: Record<string, GuidePage> = {
  'reduce-image-size-for-website': {
    slug: 'reduce-image-size-for-website',
    title: 'How to Reduce Image Size for a Website',
    searchTitle: 'Reduce Image Size for Website Uploads',
    metaDescription: 'Reduce image size for website uploads with the right compression, format, and dimension choices using a browser-based workflow.',
    description: 'A practical guide to reducing image weight before publishing to the web.',
    primaryIntent: 'reduce image size for website',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'Large images slow down pages, make CMS uploads harder, and hurt user experience. This page is built around the fastest way to shrink image files before they go live.',
    heroExample: {
      input: 'A heavy hero image or product photo heading to a website.',
      output: 'A smaller, faster-loading image with quality still acceptable for the page.',
      note: 'The goal is not “smallest possible,” but “small enough without looking bad.”',
    },
    steps: [
      'Upload the image to Image Compressor and start with moderate compression, not the strongest setting.',
      'Resize dimensions if the image is much larger than the display area on the site.',
      'Compare visual quality before downloading the optimized file.',
      'For photos, consider JPG or WebP workflows; for transparency, keep PNG where needed.',
    ],
    useCases: ['Page speed work', 'CMS uploads', 'Landing page optimization'],
    whenToUse: ['Before publishing website images', 'When file size is blocking uploads', 'When image-heavy pages feel slow'],
    avoidWhen: ['When the image is meant for print', 'When you need untouched archival quality'],
    faq: [
      { q: 'Should I resize dimensions or compress quality first?', a: 'Usually both. Start by checking if the image dimensions are far larger than the website actually displays.' },
      { q: 'What is a good website image workflow?', a: 'Choose the right format first, then compress moderately, then verify the image still looks acceptable on mobile and desktop.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Open image compressor', description: 'Reduce file size now.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Choose the right file type before exporting.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Match the format to the job.' },
    ],
    lastReviewed,
    reviewer,
  },
  'reduce-image-size-for-email': {
    slug: 'reduce-image-size-for-email',
    title: 'How to Reduce Image Size for Email',
    searchTitle: 'Reduce Image Size for Email Attachments',
    metaDescription: 'Reduce image size for email attachments and avoid oversized files with compression, resizing, and the right image format choices.',
    description: 'A quick email-focused compression workflow for oversized images.',
    primaryIntent: 'reduce image size for email',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'Email is one of the fastest places to hit file-size limits. This guide helps you shrink images for attachments without turning them into unreadable thumbnails.',
    heroExample: {
      input: 'A phone photo or screenshot that is too large to send comfortably.',
      output: 'A smaller image that still looks clear enough for inbox viewing.',
      note: 'This workflow is useful for teams, clients, and support messages that rely on screenshots or reference images.',
    },
    steps: [
      'Upload the image and start with moderate compression settings.',
      'Reduce dimensions if the image is much wider or taller than it needs to be for inbox reading.',
      'Download the optimized file and confirm it still looks clear at normal email viewing size.',
      'If you still need more savings, export a JPG from PNG where transparency is not required.',
    ],
    useCases: ['Support screenshots', 'Client attachments', 'Reference photos in inbox workflows'],
    whenToUse: ['When email rejects the file or sends slowly', 'When screenshots are larger than needed', 'When you want smaller attachments without heavy software'],
    avoidWhen: ['When the original file must remain untouched', 'When transparency is essential and email size is not a problem'],
    faq: [
      { q: 'Why are screenshots so large in email?', a: 'Screenshots can stay in PNG form with large dimensions, which makes them heavier than many email workflows need.' },
      { q: 'Should I use JPG for email?', a: 'Often yes for photos and general visuals, but keep PNG for interface shots or transparent assets when quality matters more.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Compress the image', description: 'Shrink the attachment before sending.' },
      { href: '/guides/how-to-convert-png-to-jpg/', label: 'PNG to JPG guide', description: 'Use JPG when file size matters more than transparency.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Pick the better email-friendly format.' },
    ],
    lastReviewed,
    reviewer,
  },
  'compress-images-for-shopify': {
    slug: 'compress-images-for-shopify',
    title: 'How to Compress Images for Shopify',
    searchTitle: 'Compress Images for Shopify Product Pages',
    metaDescription: 'Compress Shopify product and collection images for faster loads without wrecking visual quality using browser-based tools.',
    description: 'A Shopify-friendly image optimization workflow for product and collection pages.',
    primaryIntent: 'compress images for shopify',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'Shopify stores depend on clean product images, but large files can slow pages down and make theme sections feel heavy. This guide focuses on getting images smaller before upload.',
    heroExample: {
      input: 'A batch of product photos exported too large from a camera or design tool.',
      output: 'Smaller, store-ready images that preserve enough quality for ecommerce display.',
      note: 'The priority is a balance between trust-building visuals and faster product pages.',
    },
    steps: [
      'Compress each product image before upload, starting with moderate settings instead of maximum compression.',
      'Resize oversized images so the final dimensions match real storefront usage more closely.',
      'Keep transparency only where the product design actually needs it.',
      'Review the optimized files on a mobile-width preview before final upload.',
    ],
    useCases: ['Product pages', 'Collection pages', 'Homepage merchandising assets'],
    whenToUse: ['Before uploading product batches', 'When pages feel image-heavy', 'When you want cleaner ecommerce performance'],
    avoidWhen: ['When a print or zoom workflow needs the original large file', 'When assets will still go through major editing later'],
    faq: [
      { q: 'Should all Shopify product photos be JPG?', a: 'Not always. JPG is often the better default for photos, but PNG still matters for transparency-heavy assets.' },
      { q: 'Is resizing just as important as compression?', a: 'Yes. Oversized dimensions are a common reason ecommerce images stay heavier than they need to be.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Compress images now', description: 'Optimize product photos before upload.' },
      { href: '/guides/best-format-for-website-images/', label: 'Best format for website images', description: 'Choose formats more intentionally for ecommerce.' },
      { href: '/tools/background-remover/', label: 'Background remover', description: 'Prepare cleaner product shots before compression.' },
    ],
    lastReviewed,
    reviewer,
  },
  'compress-images-for-wordpress': {
    slug: 'compress-images-for-wordpress',
    title: 'How to Compress Images for WordPress',
    searchTitle: 'Compress Images for WordPress Uploads',
    metaDescription: 'Compress and resize WordPress images before upload to reduce page weight and make media workflows easier.',
    description: 'A pre-upload image optimization workflow for WordPress content teams.',
    primaryIntent: 'compress images for wordpress',
    language: 'en',
    toolSlug: 'image-compress',
    intro: 'WordPress content editors often upload images that are much larger than the page actually needs. This guide helps you reduce weight before the file ever touches the media library.',
    heroExample: {
      input: 'A large blog image prepared for a WordPress post.',
      output: 'A smaller, cleaner file that is easier to upload and faster on the front end.',
      note: 'This is a pre-upload optimization workflow, not a plugin replacement.',
    },
    steps: [
      'Open Image Compressor and upload the WordPress image asset before adding it to the media library.',
      'Reduce dimensions if the file is significantly larger than the article layout requires.',
      'Use moderate compression and compare clarity before download.',
      'Upload the optimized file into WordPress instead of the original large asset.',
    ],
    useCases: ['Blog cover images', 'Article screenshots', 'Feature images'],
    whenToUse: ['Before media library uploads', 'When WordPress pages feel slow', 'When editors want lighter image files without plugins'],
    avoidWhen: ['When a media automation plugin already handles the exact workflow well', 'When the file is still in an active design stage'],
    faq: [
      { q: 'Why optimize before upload instead of after?', a: 'Pre-upload optimization keeps the library cleaner and avoids publishing oversized files in the first place.' },
      { q: 'Should WordPress feature images be huge?', a: 'Not usually. Match the actual display size more closely instead of uploading unnecessarily large originals.' },
    ],
    relatedLinks: [
      { href: '/tools/image-compress/', label: 'Open image compressor', description: 'Optimize the file before it hits WordPress.' },
      { href: '/guides/reduce-image-size-for-website/', label: 'Reduce image size for a website', description: 'Use the more general workflow too.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Choose a better default format for WordPress media.' },
    ],
    lastReviewed,
    reviewer,
  },
  'remove-background-from-product-photo': {
    slug: 'remove-background-from-product-photo',
    title: 'How to Remove Background from a Product Photo',
    searchTitle: 'Remove Background from Product Photo Online',
    metaDescription: 'Remove the background from product photos online and create transparent PNGs for catalogs, listings, and design comps.',
    description: 'A product-photo-specific cutout workflow built around transparent output.',
    primaryIntent: 'remove background from product photo',
    language: 'en',
    toolSlug: 'background-remover',
    intro: 'Product images are one of the clearest use cases for fast background removal. This guide keeps the workflow focused on ecommerce and catalog-style results.',
    heroExample: {
      input: 'A product shot taken on a desk or simple backdrop.',
      output: 'A transparent PNG that can sit cleanly on white, branded, or marketplace backgrounds.',
      note: 'The simpler the product edge and background contrast, the better the quick-cut result tends to be.',
    },
    steps: [
      'Upload the product photo into Background Remover.',
      'Generate the cutout and review the edges around the item.',
      'Download the transparent PNG.',
      'Use Image Compressor if the PNG needs to be lighter for a listing or page.',
    ],
    useCases: ['Marketplace listings', 'Catalog cards', 'Promo graphics'],
    whenToUse: ['When the product needs to sit on multiple backgrounds', 'When listings need a cleaner visual presentation', 'When manual masking would take too long'],
    avoidWhen: ['When the subject has extremely complex edges', 'When the final image still requires studio-grade retouching'],
    faq: [
      { q: 'Is PNG the best output for product cutouts?', a: 'Usually yes, because PNG handles transparency well and is easy to reuse across different backgrounds.' },
      { q: 'Can I use this for complex reflective products?', a: 'Yes, but reflective or low-contrast products may still need manual cleanup after the quick cutout.' },
    ],
    relatedLinks: [
      { href: '/tools/background-remover/', label: 'Open background remover', description: 'Create the cutout now.' },
      { href: '/guides/how-to-make-a-transparent-png/', label: 'Transparent PNG guide', description: 'See the broader transparent asset workflow.' },
      { href: '/tools/image-compress/', label: 'Compress the PNG', description: 'Make the final asset lighter for storefront use.' },
    ],
    lastReviewed,
    reviewer,
  },
  'best-format-for-website-images': {
    slug: 'best-format-for-website-images',
    title: 'Best Format for Website Images',
    searchTitle: 'Best Format for Website Images: PNG, JPG, WebP, or AVIF?',
    metaDescription: 'Choose the best website image format for speed, transparency, quality, and compatibility with this practical format-selection guide.',
    description: 'A format selection guide for website image workflows across PNG, JPG, WebP, and AVIF.',
    primaryIntent: 'best format for website images',
    language: 'en',
    toolSlug: 'image-converter',
    intro: 'There is no single “best” image format for every page. This guide helps you choose based on speed, compatibility, and whether transparency matters.',
    heroExample: {
      input: 'A mix of product photos, screenshots, and graphics heading to a website.',
      output: 'A clearer format choice for each asset type instead of using one format blindly.',
      note: 'The right format is usually “best for this use case,” not “best forever.”',
    },
    steps: [
      'Use JPG for many photos and general marketing images where smaller size matters.',
      'Use PNG for transparency-heavy graphics, screenshots, and design assets that need lossless output.',
      'Use WebP when you want smaller modern web assets and the stack supports it well.',
      'Use AVIF selectively when your workflow and audience support it and you want strong compression.',
    ],
    useCases: ['Website publishing', 'CMS uploads', 'Content-team workflows'],
    whenToUse: ['When building a repeatable image workflow', 'When deciding between speed and compatibility', 'When page speed and appearance both matter'],
    avoidWhen: ['When the task is just a one-off conversion and the format is already decided', 'When the real problem is image dimensions, not format choice'],
    faq: [
      { q: 'Is WebP always the best web format?', a: 'Not always. WebP is often a strong choice, but PNG and JPG still win in some transparency, editing, or compatibility cases.' },
      { q: 'Should I use AVIF everywhere?', a: 'No. AVIF can be excellent, but support and workflow comfort still vary across teams and tools.' },
    ],
    relatedLinks: [
      { href: '/tools/image-converter/', label: 'Open image converter', description: 'Switch formats once you know the right target.' },
      { href: '/compare/png-vs-jpg/', label: 'PNG vs JPG', description: 'Compare the two most common defaults.' },
      { href: '/compare/webp-vs-png/', label: 'WebP vs PNG', description: 'Choose between smaller modern files and transparency-safe output.' },
    ],
    lastReviewed,
    reviewer,
  },
}
