import type { GuidePage } from '@/lib/discoveryTypes'
import { CONTENT_REVIEWER, LAST_REVIEWED_DATE } from '@/lib/site'

const reviewer = CONTENT_REVIEWER
const lastReviewed = LAST_REVIEWED_DATE

export const banglaGuides: Record<string, GuidePage> = {
  'bijoy-to-unicode-online': {
    slug: 'bijoy-to-unicode-online',
    title: 'Bijoy to Unicode Online',
    searchTitle: 'Bijoy to Unicode Online Converter Guide',
    metaDescription: 'Convert Bijoy Bangla text to Unicode online and understand when to use modern Unicode output for websites, apps, and documents.',
    description: 'A focused Bangla workflow page for converting legacy Bijoy text into Unicode online.',
    primaryIntent: 'bijoy to unicode online',
    language: 'bn',
    toolSlug: 'bijoy-to-unicode',
    intro: 'Use this page when you have Bangla text from older Bijoy-based systems and need clean Unicode output for websites, messaging apps, modern documents, or web publishing.',
    heroExample: {
      input: 'Legacy Bijoy or SutonnyMJ text from an older publication workflow.',
      output: 'Unicode Bangla that behaves better in modern editors, websites, and mobile devices.',
      note: 'This is one of the clearest search-intent matches on the site.',
    },
    steps: [
      'Open the Bijoy to Unicode tool and paste the source text into the input area.',
      'Run the conversion in the browser and review the converted Bangla output.',
      'Copy the Unicode result into your website, document, or app.',
      'Proofread the destination workflow if the original source came from a very old DTP setup.',
    ],
    useCases: ['Web publishing', 'CMS editing', 'Modern document workflows'],
    whenToUse: ['When Bangla text came from a Bijoy source', 'When you need Unicode output for modern systems', 'When pasted text breaks in websites or apps'],
    avoidWhen: ['When the problem is image text or OCR', 'When the source text is already valid Unicode'],
    faq: [
      { q: 'Why convert Bijoy to Unicode?', a: 'Unicode is more reliable across modern devices, websites, mobile apps, and collaborative editors.' },
      { q: 'Do I still need proofreading?', a: 'Yes. Most cases convert well, but older or heavily styled source text still deserves a quick manual review.' },
    ],
    relatedLinks: [
      { href: '/tools/bijoy-to-unicode/', label: 'Open Bijoy to Unicode', description: 'Run the conversion now.' },
      { href: '/compare/bijoy-vs-unicode/', label: 'Bijoy vs Unicode', description: 'See when each workflow makes sense.' },
      { href: '/guides/fix-broken-bangla-font-conversion/', label: 'Fix broken Bangla font conversion', description: 'Troubleshoot messy outputs.' },
    ],
    lastReviewed,
    reviewer,
  },
  'unicode-to-bijoy-online': {
    slug: 'unicode-to-bijoy-online',
    title: 'Unicode to Bijoy Online',
    searchTitle: 'Unicode to Bijoy Online Converter Guide',
    metaDescription: 'Convert Unicode Bangla text to Bijoy online when a legacy Bangla publishing workflow still requires older keyboard or font conventions.',
    description: 'A practical Unicode to Bijoy workflow for legacy publishing needs.',
    primaryIntent: 'unicode to bijoy online',
    language: 'bn',
    toolSlug: 'unicode-to-bijoy',
    intro: 'Use this page when your source Bangla text is already modern Unicode, but the next publishing workflow still expects Bijoy or older layout compatibility.',
    heroExample: {
      input: 'Unicode Bangla typed in Avro or a modern editor.',
      output: 'Bijoy-compatible text for older design or publishing environments.',
      note: 'This is a transitional workflow, not the ideal long-term publishing format.',
    },
    steps: [
      'Open Unicode to Bijoy and paste the Unicode Bangla text.',
      'Run the conversion and check the output in the preview area.',
      'Copy the result into the target legacy publishing workflow.',
      'Verify the final text inside the destination software before export or print.',
    ],
    useCases: ['Legacy DTP handoff', 'Older publication systems', 'Mixed modern-to-legacy Bangla teams'],
    whenToUse: ['When the next app truly requires Bijoy', 'When a client or editor still works in a legacy Bangla setup', 'When modern Unicode text must be handed back into an old production process'],
    avoidWhen: ['When your destination already supports Unicode properly', 'When you only need web or mobile-safe Bangla'],
    faq: [
      { q: 'Should I keep using Bijoy long term?', a: 'For the web and most modern apps, Unicode is better. This page is for compatibility with older workflows.' },
      { q: 'Can conversion fix every font issue automatically?', a: 'Not always. Some destination layouts still need manual checking depending on the font and app in use.' },
    ],
    relatedLinks: [
      { href: '/tools/unicode-to-bijoy/', label: 'Open Unicode to Bijoy', description: 'Convert the text now.' },
      { href: '/compare/bijoy-vs-unicode/', label: 'Bijoy vs Unicode', description: 'Understand when each is appropriate.' },
      { href: '/guides/fix-broken-bangla-font-conversion/', label: 'Fix broken Bangla conversion', description: 'Troubleshoot font and destination-app issues after conversion.' },
    ],
    lastReviewed,
    reviewer,
  },
  'bijoy-to-unicode-for-illustrator': {
    slug: 'bijoy-to-unicode-for-illustrator',
    title: 'Bijoy to Unicode for Illustrator Workflows',
    searchTitle: 'Bijoy to Unicode for Illustrator',
    metaDescription: 'Convert Bijoy text to Unicode before using it in Illustrator-adjacent modern publishing or web workflows.',
    description: 'A DTP-oriented Bangla page built around Illustrator-era legacy text handoff.',
    primaryIntent: 'bijoy to unicode for illustrator',
    language: 'bn',
    toolSlug: 'bijoy-to-unicode',
    intro: 'Many Bangla publishing workflows still move through Illustrator-adjacent or legacy design systems. This page is for converting old Bijoy text into safer Unicode before modern reuse.',
    heroExample: {
      input: 'Bijoy text copied from an older layout or Illustrator-era production source.',
      output: 'Unicode Bangla ready for websites, modern docs, or updated creative workflows.',
      note: 'The real job here is compatibility cleanup before the next stage.',
    },
    steps: [
      'Paste the source Bijoy text into the converter.',
      'Generate the Unicode output in the browser.',
      'Test the result in the next modern editor or publishing app.',
      'Proofread any complex conjuncts if the source came from a very old layout setup.',
    ],
    useCases: ['Legacy design handoff', 'Editorial cleanup', 'Modern web reuse of older Bangla copy'],
    whenToUse: ['When Illustrator-adjacent legacy text needs modern reuse', 'When pasted Bangla breaks in newer apps', 'When moving old DTP copy to the web'],
    avoidWhen: ['When the destination still requires Bijoy', 'When the issue is image-based text rather than encoding'],
    faq: [
      { q: 'Why not keep the old Bijoy workflow?', a: 'Because Unicode is safer for modern publishing, sharing, and cross-device readability.' },
      { q: 'Does this replace design proofreading?', a: 'No. It improves compatibility, but layout review still matters in production work.' },
    ],
    relatedLinks: [
      { href: '/tools/bijoy-to-unicode/', label: 'Open Bijoy to Unicode', description: 'Run the conversion now.' },
      { href: '/guides/bijoy-to-unicode-online/', label: 'Bijoy to Unicode online', description: 'Use the simpler general workflow too.' },
      { href: '/compare/bijoy-vs-unicode/', label: 'Bijoy vs Unicode', description: 'See why the conversion matters.' },
    ],
    lastReviewed,
    reviewer,
  },
  'unicode-to-bijoy-for-photoshop': {
    slug: 'unicode-to-bijoy-for-photoshop',
    title: 'Unicode to Bijoy for Photoshop Workflows',
    searchTitle: 'Unicode to Bijoy for Photoshop',
    metaDescription: 'Convert Unicode Bangla to Bijoy when older Photoshop-era or legacy Bangla publishing workflows still require it.',
    description: 'A design-specific Unicode to Bijoy page for older production environments.',
    primaryIntent: 'unicode to bijoy for photoshop',
    language: 'bn',
    toolSlug: 'unicode-to-bijoy',
    intro: 'Use this page when the next production step still depends on an older Photoshop-era Bangla workflow that expects Bijoy-compatible text.',
    heroExample: {
      input: 'Unicode Bangla typed in a modern editor or website.',
      output: 'Bijoy-style text for a legacy design or publishing setup.',
      note: 'This is a compatibility bridge, not the best long-term web format.',
    },
    steps: [
      'Paste the Unicode Bangla text into Unicode to Bijoy.',
      'Convert the text in the browser and review the output.',
      'Paste the result into the target design workflow and confirm rendering there.',
      'Keep the original Unicode source if you also need a web-safe version later.',
    ],
    useCases: ['Legacy design handoff', 'Older publishing teams', 'Mixed Bangla production environments'],
    whenToUse: ['When Photoshop-era or legacy setups still require Bijoy', 'When clients or teammates insist on older text standards', 'When you need a bridge between modern typing and old production'],
    avoidWhen: ['When the destination accepts Unicode already', 'When the goal is web publishing or mobile readability'],
    faq: [
      { q: 'Is Unicode still better for the web?', a: 'Yes. This page is for legacy workflow compatibility, not for replacing Unicode on modern platforms.' },
      { q: 'Will the final design still need checking?', a: 'Yes. Always review the output in the destination design tool before final export or print.' },
    ],
    relatedLinks: [
      { href: '/tools/unicode-to-bijoy/', label: 'Open Unicode to Bijoy', description: 'Run the converter now.' },
      { href: '/guides/unicode-to-bijoy-online/', label: 'Unicode to Bijoy online', description: 'Use the general workflow too.' },
      { href: '/compare/bijoy-vs-unicode/', label: 'Choose the right standard', description: 'Compare the two Bangla workflow types.' },
    ],
    lastReviewed,
    reviewer,
  },
  'avro-unicode-to-bijoy': {
    slug: 'avro-unicode-to-bijoy',
    title: 'Convert Avro Unicode to Bijoy',
    searchTitle: 'Convert Avro Unicode to Bijoy Online',
    metaDescription: 'Convert Avro-style Unicode Bangla text to Bijoy online for legacy publishing and old desktop workflows.',
    description: 'A practical Bangla conversion page for Avro and other Unicode-first typing habits.',
    primaryIntent: 'avro unicode to bijoy',
    language: 'bn',
    toolSlug: 'unicode-to-bijoy',
    intro: 'Many Bangla users type with Avro or other Unicode-first tools but still have to deliver copy into Bijoy-based legacy systems. This guide is built for that bridge.',
    heroExample: {
      input: 'Bangla text typed with Avro in a modern editor.',
      output: 'Bijoy-compatible text for older publishing apps.',
      note: 'This is one of the clearest real-world Bangla handoff problems on the site.',
    },
    steps: [
      'Copy the Avro-typed Unicode Bangla text.',
      'Paste it into Unicode to Bijoy and run the conversion.',
      'Review the result and move it into the target older workflow.',
      'Check the final font/rendering in the destination environment before delivery.',
    ],
    useCases: ['Avro to legacy DTP handoff', 'Unicode-first typing to Bijoy delivery', 'Mixed-generation publishing teams'],
    whenToUse: ['When the source is Avro Unicode', 'When the next workflow still requires Bijoy', 'When old publishing software blocks Unicode-first text'],
    avoidWhen: ['When your full workflow already supports Unicode', 'When the issue is font installation, not text standard conversion'],
    faq: [
      { q: 'Does Avro text need conversion for modern websites?', a: 'No. Avro Unicode is already well suited to modern web use; conversion is only for legacy targets.' },
      { q: 'Can I skip the final proofread?', a: 'No. Always review text in the destination software if it is heading into an older publishing workflow.' },
    ],
    relatedLinks: [
      { href: '/tools/unicode-to-bijoy/', label: 'Open Unicode to Bijoy', description: 'Convert Avro-style Unicode text now.' },
      { href: '/guides/unicode-to-bijoy-online/', label: 'Unicode to Bijoy online', description: 'Use the general workflow too.' },
      { href: '/compare/bijoy-vs-unicode/', label: 'Bijoy vs Unicode', description: 'Understand the standards behind the conversion.' },
    ],
    lastReviewed,
    reviewer,
  },
  'fix-broken-bangla-font-conversion': {
    slug: 'fix-broken-bangla-font-conversion',
    title: 'How to Fix Broken Bangla Font Conversion',
    searchTitle: 'Fix Broken Bangla Font Conversion Online',
    metaDescription: 'Troubleshoot broken Bangla font conversion between Bijoy and Unicode with practical checks for source text, target apps, and proofing.',
    description: 'A troubleshooting page for messy Bangla conversion outputs and font-related confusion.',
    primaryIntent: 'fix broken bangla font conversion',
    language: 'bn',
    toolSlug: 'bangla-converter',
    intro: 'Sometimes the conversion is not truly “wrong”; the source encoding, target font, or destination app is the real problem. This page focuses on troubleshooting the usual failure points quickly.',
    heroExample: {
      input: 'Bangla text that looks broken after moving between Bijoy and Unicode workflows.',
      output: 'A cleaner diagnosis of whether the issue is the source encoding, the converter direction, or the destination font/app.',
      note: 'This page helps keep users from blaming the wrong step.',
    },
    steps: [
      'Confirm whether the source text started as Bijoy or Unicode before converting.',
      'Use the correct conversion direction in the Bangla converter.',
      'Paste the result into a known-good modern editor to compare behavior.',
      'If the output still looks broken, review the destination font and app support rather than assuming the text is invalid.',
    ],
    useCases: ['Troubleshooting publishing handoff', 'Fixing pasted text issues', 'Checking encoding direction mistakes'],
    whenToUse: ['When the converted text looks wrong', 'When one app shows broken text but another does not', 'When you are unsure whether the problem is encoding or font support'],
    avoidWhen: ['When the source text is actually an image', 'When you already know the destination app fully supports the target standard'],
    faq: [
      { q: 'What causes broken Bangla conversion most often?', a: 'Wrong source assumption, wrong conversion direction, legacy font dependence, or destination app rendering issues are the usual causes.' },
      { q: 'Is the converter always the problem?', a: 'No. Many “broken” cases are really font or destination-environment problems, not raw conversion failures.' },
    ],
    relatedLinks: [
      { href: '/tools/bangla-converter/', label: 'Open Bangla converter', description: 'Test the source text with the right direction.' },
      { href: '/guides/bijoy-to-unicode-online/', label: 'Bijoy to Unicode online', description: 'Use the most common modern cleanup path.' },
      { href: '/guides/unicode-to-bijoy-online/', label: 'Unicode to Bijoy online', description: 'Use the legacy handoff path when needed.' },
    ],
    lastReviewed,
    reviewer,
  },
}
